version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - sd2k
  assignees:
  - sd2k
  groups:
    rust-dependencies:
      patterns:
        - "*"
